archives:
- format: binary
builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - arm64
    - amd64
dockers:
  - image_templates:
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:arm64-{{ .Env.GITHUB_SHA }}"
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:arm64-{{ .Tag }}"
    goos: linux
    goarch: arm64
  - image_templates:
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:amd64-{{ .Env.GITHUB_SHA }}"
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:amd64-{{ .Tag }}"
    goos: linux
    goarch: amd64
release:
  footer: |
    ## Docker Images
    - `us-docker.pkg.dev/umeedefi/stack/fonzie:arm64-{{ .Env.GITHUB_SHA }}`
    - `us-docker.pkg.dev/umeedefi/stack/fonzie:arm64-{{ .Tag }}`
    - `us-docker.pkg.dev/umeedefi/stack/fonzie:amd64-{{ .Env.GITHUB_SHA }}`
    - `us-docker.pkg.dev/umeedefi/stack/fonzie:amd64-{{ .Tag }}`
