archives:
- format: binary
builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - arm64
    - amd64

dockers:
  - image_templates:
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:{{ .Env.GITHUB_SHA }}"
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:{{ .Tag }}"
    - "us-docker.pkg.dev/umeedefi/stack/fonzie:latest"
    goos: linux
    goarch:
    - arm64
    - amd64
