name: goreleaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+(-rc[0-9]+)?" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GAR_JSON_BASE64_KEY }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: docker/setup-buildx-action@v1
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
